# Generated by Django 5.1.6 on 2025-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('job_finder', 'Job Finder')], default='job_finder', max_length=10),
        ),
    ]
