# Generated by Django 5.1.6 on 2025-05-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.TextField(default='review'),
        ),
    ]
